# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "redhat-64"

  config.vm.provider :vmware_workstation do |v, override|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    v.gui = true
   #v.vmx["memsize"]  = "2048"
   #v.vmx["numvcpus"] = "2"

    # eth1
    v.vmx["ethernet1.present"]        = "TRUE"
    v.vmx["ethernet1.vnet"]           = "VMnet11"
    v.vmx["ethernet1.connectionType"] = "custom"
    v.vmx["ethernet1.virtualDev"]     = "e1000"
    v.vmx["ethernet1.wakeOnPcktRcv"]  = "FALSE"
    v.vmx["ethernet1.addressType"]    = "generated"

    # eth2
    v.vmx["ethernet2.present"]        = "TRUE"
    v.vmx["ethernet2.vnet"]           = "VMnet12"
    v.vmx["ethernet2.connectionType"] = "custom"
    v.vmx["ethernet2.virtualDev"]     = "e1000"
    v.vmx["ethernet2.wakeOnPcktRcv"]  = "FALSE"
    v.vmx["ethernet2.addressType"]    = "generated"

    # eth3
    v.vmx["ethernet3.present"]        = "TRUE"
    v.vmx["ethernet3.vnet"]           = "VMnet13"
    v.vmx["ethernet3.connectionType"] = "custom"
    v.vmx["ethernet3.virtualDev"]     = "e1000"
    v.vmx["ethernet3.wakeOnPcktRcv"]  = "FALSE"
    v.vmx["ethernet3.addressType"]    = "generated"
  end

 #config.vm.provision "shell", path: "bootstrap.sh"
end
