# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6-x86_64"

  config.vm.provider :virtualbox do |v, override|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # bond0: eth1, eth2
    v.customize ["modifyvm", :id, "--nic2",   "intnet"]
    v.customize ["modifyvm", :id, "--nic3",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet2", "bond0"]
    v.customize ["modifyvm", :id, "--intnet3", "bond0"]
    # bond1: eth3, eth4
    v.customize ["modifyvm", :id, "--nic4",   "intnet"]
    v.customize ["modifyvm", :id, "--nic5",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet4", "bond1"]
    v.customize ["modifyvm", :id, "--intnet5", "bond1"]
    # bond2: eth5, eth6
    v.customize ["modifyvm", :id, "--nic6",   "intnet"]
    v.customize ["modifyvm", :id, "--nic7",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet6", "bond2"]
    v.customize ["modifyvm", :id, "--intnet7", "bond2"]
  end
end
